osx_image: xcode9
language: objective-c

script:
- set -o pipefail
- xcodebuild test -configuration Release -enableCodeCoverage YES -workspace Example/RxTheme.xcworkspace -scheme RxTheme-Example -destination 'OS=11.0,name=iPhone X' ONLY_ACTIVE_ARCH=NO | xcpretty
